//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class habilidad
    {
        public int id { get; set; }
        public int idsubarea { get; set; }
        public int idexperto { get; set; }
    
        public virtual datopersonal datopersonal { get; set; }
        public virtual subarea subarea { get; set; }
    }
}
