//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarea
    {
        public tarea()
        {
            this.asignacion = new HashSet<asignacion>();
            this.calificacion = new HashSet<calificacion>();
        }
    
        public int id { get; set; }
        public string contacto { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string foto1 { get; set; }
        public string foto2 { get; set; }
        public string foto3 { get; set; }
        public string foto4 { get; set; }
        public int idsubarea { get; set; }
        public System.DateTime fecharegistro { get; set; }
        public Nullable<System.DateTime> fechapublicado { get; set; }
        public decimal valorestimado { get; set; }
        public byte[] direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<asignacion> asignacion { get; set; }
        public virtual ICollection<calificacion> calificacion { get; set; }
        public virtual subarea subarea { get; set; }
        public virtual estadoTarea estadoTarea { get; set; }
    }
}
